### ISSUE TITLE
Use `istio.io/istio/pkg/log` instead of `klog` and `fmt`

### ISSUE THREAD

**Issue by jewertow** [jewertow/federation#16]
Currently we use `klog` and `fmt` to print logs, but we have to unify logging and use proper levels.

I think that we could import `istio.io/istio/pkg/log`, because it has a few advantages over `klog`:
1) It's a wrapper for `zap` library, so it has very good performance.
2) Log levels like info / warn / error / debug are more intuitive than numeric values in `klog`.
3) It provides nice scope API, so we can set desired log level for particular components.

Additionally, we should use the same command line argument, like Istio, i.e. `--log_output_level`. It may also require to replace `flag` with `spf13/cobra`, but I am not 100% sure.

**Comment by yxun** [comment]
I did some experiments about replacing `klog` with `istio.io/istio/pkg/log` . 
The istio/pkg/log is part of `istio.io/istio` module. There are cross dependencies among existing ones in this federation go.mod. So whenever running a `go get`, it will update other deps versions such as istio.io/api, github.com/envoy/proxy/go-control-plance etc.

There is no straight-forward way to find a `istio.io/istio/pkg/log` version SHA according to Istio v1.22.2 release.
We may keep a copy of https://github.com/istio/istio/tree/1.22.2/pkg/log in this federation repo and then we can use it as `github.com/jewertow/federation/internal/pkg/log`
  
Reference: https://pkg.go.dev/istio.io/istio/pkg

**Comment by jewertow** [comment]
> The istio/pkg/log is part of istio.io/istio module.

Yes, of course. I imported `istio.io/istio`, because I need test framework, so it should be much easier now.

**Comment by yxun** [comment]
> Additionally, we should use the same command line argument, like Istio, i.e. --log_output_level. It may also require to replace flag with spf13/cobra, 

The logging configuration is from its `init` function when importing that log package:
https://github.com/istio/istio/blob/master/pkg/log/config.go#L115

So we need to configure a `log.Options` . The existing CLI arguments are parsed from this method:
https://github.com/istio/istio/blob/master/pkg/log/options.go#L201
It is calling the following method `func (o *Options) AttachFlags`
Here is an example when starting pilot:
https://github.com/istio/istio/blob/master/pilot/cmd/pilot-discovery/app/cmd.go#L192

It will get complicated by introducing `cobra.Command` in our main.go. I see we are using built-in `flag` package for parsing CLI arguments now. I can follow the existing main start logic to avoid additional complicity for review.

Do we want to use  `cobra.Command` and refactor our main.go start process ? 
I am not quite sure about that change and I'd like to plan that in another issue PR later

I will create a PR about logging tomorrow

**Comment by yxun** [comment]
PR ready for review in https://github.com/jewertow/federation/pull/23  `make e2e` ok
Currently each handler or controller logging is using the DefaultOption. And the command line logging arguments values are stored in the rootCommand scope.

Do we need each component scope (e.g. handle, controller etc.) logging config ? 
I can add a `*log.Options` field in the package config `Federation` struct or add a separate struct there.

**Comment by jewertow** [comment]
Done in #23
