### ISSUE TITLE
Implement exported service watcher

### ISSUE THREAD

**Issue by jewertow** [jewertow/federation#2]
Exported service watcher should watch k8s Services matching specified label selectors and trigger MCP update on create/delete events. For instance, a create event should result in sending updated Gateway resource with new Service DNS name appended to the `spec.servers[0].hosts`. The watcher should send new MCP resources to the XDS server via a channel or calling proper method, but should not handle XDS protocol itself.

**Comment by matteo-casalino** [comment]
I should have some time to take this one in the coming days, unless already taken?
